site_name: RainyDay
pages:
  - Home: index.md
  - Tutorial:
      - 'Start' : 'tutorial_start.md'
  - Linux: linux.md
  - About: about.md

repo_url : https://github.com/luxinator/RainyDay

site_description : Apache Spark NiFi HDFS Solr Tutorial HowTo