site_name: RainyDay
pages:
  - Home: index.md
  - Tutorial:
      - 'Start' : 'tutorial_start.md'
      - 'Spark' : 'spark01.md'
      - 'NiFi' : nifi.md
      - 'HDFS' : HDFS.md
      - 'Solr' : solr.md
      - 'Scala' : scala.md
  - Linux: linux.md
  - About: about.md

repo_url : https://github.com/luxinator/RainyDay

site_description : Apache Spark NiFi HDFS Solr Tutorial HowTo IntelliJ Scala